// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lb2Backend struct {
	_     structs.HostLayout
	Ip    uint32
	Port  uint16
	_     [2]byte
	Conns uint32
}

type lb2ConnMeta struct {
	_           structs.HostLayout
	Ip          uint32
	Port        uint16
	_           [2]byte
	BackendIdx  uint32
	State       uint8
	_           [1]byte
	ServicePort uint16
}

type lb2IpPort struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	_    [2]byte
}

// loadLb2 returns the embedded CollectionSpec for lb2.
func loadLb2() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lb2Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb2: %w", err)
	}

	return spec, err
}

// loadLb2Objects loads lb2 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lb2Objects
//	*lb2Programs
//	*lb2Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLb2Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb2()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lb2Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb2Specs struct {
	lb2ProgramSpecs
	lb2MapSpecs
	lb2VariableSpecs
}

// lb2ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb2ProgramSpecs struct {
	XdpLoadBalancer *ebpf.ProgramSpec `ebpf:"xdp_load_balancer"`
}

// lb2MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb2MapSpecs struct {
	BackendCount  *ebpf.MapSpec `ebpf:"backend_count"`
	Backends      *ebpf.MapSpec `ebpf:"backends"`
	Conntrack     *ebpf.MapSpec `ebpf:"conntrack"`
	FreePorts     *ebpf.MapSpec `ebpf:"free_ports"`
	PortOwnership *ebpf.MapSpec `ebpf:"port_ownership"`
	Services      *ebpf.MapSpec `ebpf:"services"`
}

// lb2VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb2VariableSpecs struct {
}

// lb2Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLb2Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb2Objects struct {
	lb2Programs
	lb2Maps
	lb2Variables
}

func (o *lb2Objects) Close() error {
	return _Lb2Close(
		&o.lb2Programs,
		&o.lb2Maps,
	)
}

// lb2Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLb2Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb2Maps struct {
	BackendCount  *ebpf.Map `ebpf:"backend_count"`
	Backends      *ebpf.Map `ebpf:"backends"`
	Conntrack     *ebpf.Map `ebpf:"conntrack"`
	FreePorts     *ebpf.Map `ebpf:"free_ports"`
	PortOwnership *ebpf.Map `ebpf:"port_ownership"`
	Services      *ebpf.Map `ebpf:"services"`
}

func (m *lb2Maps) Close() error {
	return _Lb2Close(
		m.BackendCount,
		m.Backends,
		m.Conntrack,
		m.FreePorts,
		m.PortOwnership,
		m.Services,
	)
}

// lb2Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLb2Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb2Variables struct {
}

// lb2Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLb2Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb2Programs struct {
	XdpLoadBalancer *ebpf.Program `ebpf:"xdp_load_balancer"`
}

func (p *lb2Programs) Close() error {
	return _Lb2Close(
		p.XdpLoadBalancer,
	)
}

func _Lb2Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb2_bpf.o
var _Lb2Bytes []byte
