// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lbBackend struct {
	_     structs.HostLayout
	Ip    uint32
	Port  uint16
	_     [2]byte
	Conns uint32
}

type lbConnMeta struct {
	_           structs.HostLayout
	Ip          uint32
	Port        uint16
	_           [2]byte
	BackendIdx  uint32
	State       uint8
	_           [1]byte
	ServicePort uint16
}

type lbIpPort struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	_    [2]byte
}

// loadLb returns the embedded CollectionSpec for lb.
func loadLb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb: %w", err)
	}

	return spec, err
}

// loadLbObjects loads lb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lbObjects
//	*lbPrograms
//	*lbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbSpecs struct {
	lbProgramSpecs
	lbMapSpecs
	lbVariableSpecs
}

// lbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbProgramSpecs struct {
	XdpLoadBalancer *ebpf.ProgramSpec `ebpf:"xdp_load_balancer"`
}

// lbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbMapSpecs struct {
	BackendCount  *ebpf.MapSpec `ebpf:"backend_count"`
	Backends      *ebpf.MapSpec `ebpf:"backends"`
	Conntrack     *ebpf.MapSpec `ebpf:"conntrack"`
	FreePorts     *ebpf.MapSpec `ebpf:"free_ports"`
	PortOwnership *ebpf.MapSpec `ebpf:"port_ownership"`
	Services      *ebpf.MapSpec `ebpf:"services"`
}

// lbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbVariableSpecs struct {
}

// lbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbObjects struct {
	lbPrograms
	lbMaps
	lbVariables
}

func (o *lbObjects) Close() error {
	return _LbClose(
		&o.lbPrograms,
		&o.lbMaps,
	)
}

// lbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbMaps struct {
	BackendCount  *ebpf.Map `ebpf:"backend_count"`
	Backends      *ebpf.Map `ebpf:"backends"`
	Conntrack     *ebpf.Map `ebpf:"conntrack"`
	FreePorts     *ebpf.Map `ebpf:"free_ports"`
	PortOwnership *ebpf.Map `ebpf:"port_ownership"`
	Services      *ebpf.Map `ebpf:"services"`
}

func (m *lbMaps) Close() error {
	return _LbClose(
		m.BackendCount,
		m.Backends,
		m.Conntrack,
		m.FreePorts,
		m.PortOwnership,
		m.Services,
	)
}

// lbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbVariables struct {
}

// lbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbPrograms struct {
	XdpLoadBalancer *ebpf.Program `ebpf:"xdp_load_balancer"`
}

func (p *lbPrograms) Close() error {
	return _LbClose(
		p.XdpLoadBalancer,
	)
}

func _LbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb_bpf.o
var _LbBytes []byte
